[package]
name = "unshorten"
version = "0.1.0"
authors = ["a.swaving@gmail.com <a.swaving@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
http_req = "0.5.1"

[build-dependencies]
skeptic = "0.13.4"

[dev-dependencies]
skeptic = "0.13.4"
